version: '3.8'
services:
  cometa-frame:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Next.js
    environment:
      - NODE_ENV=production
    command: pnpm start
